language: elixir
sudo: false
elixir:
  - 1.7
  - 1.8
otp_release:
  - 21.3
env:
  - MIX_ENV=test
script:
  - mix coveralls.travis
services:
  - postgresql
  - redis-server
cache:
  directories:
    - ~/.mix
    - ~/.hex
before_script:
  - psql -c "CREATE DATABASE flippant_test;" -U postgres
addons:
  postgresql: "9.6"
jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
      elixir: 1.8
    - stage: credo
      env:
        - MIX_ENV=dev
      script: mix credo --strict
      elixir: 1.8
    - stage: dialyzer
      env:
        - MIX_ENV=dev
      before_script: travis_wait mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
      elixir: 1.8
